name: LZ5 codec tests
on: [push, pull_request]
jobs:
  frames:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2025-vs2026, windows-11-arm]
        optimization: [O1, Od]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - name: Compile and test LZ5 frames
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -property installationPath`) do set VSROOT=%%i
          set ARCH=x64
          if "${{ matrix.runner }}" == "windows-11-arm" set ARCH=arm64
          call "%VSROOT%\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
          mkdir lz5-test-build
          cd lz5-test-build
          cl /nologo /${{ matrix.optimization }} /Gy /Gw /GS- /I..\C\lz5 /I..\C\hashes ..\tests\lz5-frame.c ..\C\lz5\lz5.c ..\C\lz5\lz5hc.c ..\C\lz5\lz5frame.c ..\C\hashes\xxhash.c /Fe:lz5-frame.exe
          if errorlevel 1 exit /b 1
          lz5-frame.exe
